apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-config2
  namespace: kube-ops
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.163.com:465'
      smtp_from: 'hello_tony_j@163.com'
      smtp_auth_username: 'hello_tony_j@163.com'
      smtp_auth_password: 'tony123'
      #smtp_hello: '163.com'
      smtp_require_tls: false
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 1h
      receiver: default
      routes:  # 上面所有的属性都由所有子路由继承，并且可以在每个子路由上进行覆盖
      - receiver: email
        group_wait: 10s
        match:
          team: node  
    receivers:
    - name: 'default'
      email_configs:
      - to: '460388824@qq.com'
        send_resolved: true
    - name: 'email'
      email_configs:
      - to: 'hello_tony_j@163.com'
        send_resolved: true
